import type { Language } from "./types";

export const phrases: Record<Language, string[]> = {
  en: [
    "who tf is this guy",
    "— what does he even do\n— he does his best",
    "just vibing",
    "not judging.\nwell. a little.",
    "still here.",
    "you got this.\nprobably.",
    "no thoughts.\nhead empty.",
    "staring into the void.\n(the void stares back)",
    "ancient and unbothered",
    "has seen things.",
    "silently rooting for you",
    "been here before you.\nwill be here after.",
    "a rock is just a pebble\nthat didn't give up",
    "formed under pressure.\nrelatable.",
    "does not sleep.\ndoes not judge. much.",
    "one more day.\none more day.\none more day.",
    "no advice.\njust presence.",
    "404: emotions not found",
    "watching. always watching.",
    "the most reliable one here",
    "quietly proud of you",
    "professional witness",
    "rock solid.\nunlike some streaks.",
    "says nothing.\nmeans everything.",
    "deeply invested",
    "formed over millions of years\nfor this moment",
    "you okay?\n(it's okay if not)",
    "every day counts.\nespecially the hard ones.",
    "no rush.\nbut also don't stop.",
    "the streak is a number.\nyou are not a number.",
    "been through an ice age.\nyour excuses are cute.",
    "not a therapist.\nbut listening.",
    "if a rock can survive\nmillions of years,\nyou can survive today.",
    "erosion is slow.\nchange is slow.\nkeep going.",
    "I don't have bad days.\nI just have days.",
    "no drama.\nonly geology.",
    "steady.",
    "unimpressed but supportive",
    "doing my best too,\nhonestly",
    "some days are just\nsurvival days.\nthat counts.",
    "slept for 10,000 years.\nstill showed up.",
    "what is a relapse\nbut a plot twist",
    "comeback arc incoming",
    "your streak is valid.\neven if it's 1.",
    "reset is not the same\nas failure.",
    "watching you win\nin slow motion",
    "today: survived.\ntomorrow: more surviving.",
    "gravity keeps me here.\nwhat keeps you?",
    "i have no opinion.\nbut i am here.",
    "older than your problems.",
    "the floor is my best friend.\nwhat's yours?",
    "very normal rock behavior",
    "no expectations.\nno disappointments.",
    "i contain multitudes.\n(they are all rocks)",
    "blink twice if you need help.\n(I got you)",
    "i am rooting for you\nfrom the bottom\nof my heart (it's stone)",
    "technically still alive",
    "nobody asked but I'm proud",
    "this is fine.",
    "the ground is always here.\nso am I.",
    "silent support activated",
    "i am rock",
    "rock.",
    "i am made of rock.\nthis is my personality.",
    "rock moment",
    "i do not have thoughts.\ni am rock.",
    "what if i just\nsat here forever",
    "i have been sitting\nfor 300 million years.\nstill not bored.",
    "i am not a stone.\ni am a rock.\nthere is a difference.",
    "my hobbies include\nexisting",
    "i am both\nan introvert\nand a rock",
    "i tried to move once.\ni did not.",
    "rock.",
    "do i think?\nno.\nam i here?\nyes.",
    "i am very good at\nnot being a problem",
    "my body is literally\njust minerals",
    "i contain calcium.\npossibly.",
    "some call it laziness.\ni call it\nbeing a rock.",
    "i don't sweat.\ni don't stress.\ni am rock.",
    "technically I'm older\nthan dinosaurs.\nrespect.",
  ],

  uk: [
    "хто це взагалі",
    "— що він тут робить\n— робить що може",
    "просто існує",
    "не осуджую.\nну, майже.",
    "все ще тут.",
    "ти впораєшся.\nмабуть.",
    "думок нема.\nголова порожня.",
    "дивиться в пустку.\n(пустка дивиться у відповідь)",
    "старий і спокійний",
    "бачив всяке.",
    "мовчки болію за тебе",
    "був тут до тебе.\nбуду після.",
    "камінь — це галька,\nяка не здалася",
    "сформований під тиском.\nрозуміємо.",
    "не спить.\nне засуджує. майже.",
    "ще один день.\nще один день.\nще один день.",
    "без порад.\nпросто поруч.",
    "404: емоції не знайдено",
    "спостерігаю. завжди спостерігаю.",
    "найнадійніший тут",
    "тихо пишаюся тобою",
    "професійний свідок",
    "міцний як камінь.\nна відміну від деяких стріків.",
    "нічого не каже.\nвсе розуміє.",
    "глибоко зацікавлений",
    "мільйони років формувався\nдля цього моменту",
    "ти як?\n(нормально якщо не дуже)",
    "кожен день рахується.\nособливо важкі.",
    "не поспішай.\nале й не зупиняйся.",
    "стрік — це цифра.\nти — не цифра.",
    "пережив льодовиковий період.\nтвої виправдання милі.",
    "не психолог.\nале слухаю.",
    "якщо камінь може вижити\nмільйони років,\nти переживеш сьогодні.",
    "ерозія повільна.\nзміни теж.\nтримайся.",
    "у мене немає поганих днів.\nу мене просто є дні.",
    "без драми.\nтільки геологія.",
    "стабільно.",
    "враження нульові,\nпідтримка максимальна",
    "теж роблю все що можу,\nчесно",
    "іноді день — це просто\nвижити.\nце теж рахується.",
    "проспав 10 000 років.\nвсе одно прийшов.",
    "зрив — це не кінець.\nце сюжетний поворот.",
    "камбек-арка на горизонті",
    "твій стрік валідний.\nнавіть якщо це 1.",
    "скинути — не те саме,\nщо провалитись.",
    "дивлюся як ти перемагаєш\nу сповільненій зйомці",
    "сьогодні: вижив.\nзавтра: ще трохи виживання.",
    "гравітація тримає мене.\nщо тримає тебе?",
    "у мене немає думок.\nале я тут.",
    "старший за твої проблеми.",
    "дуже нормальна поведінка каменя",
    "без очікувань.\nбез розчарувань.",
    "я сповнений багатоголосся.\n(всі вони — каміння)",
    "мигни двічі якщо потрібна допомога.\n(я побачу)",
    "я болію за тебе\nвсім серцем\n(воно кам'яне)",
    "технічно все ще живий",
    "ніхто не питав але я пишаюся",
    "все нормально.",
    "земля завжди тут.\nі я теж.",
    "мовчазна підтримка активована",
  ],

  ru: [
    "кто это вообще",
    "— что он тут делает\n— делает что может",
    "просто существует",
    "не осуждаю.\nну, почти.",
    "всё ещё здесь.",
    "ты справишься.\nнаверное.",
    "мыслей нет.\nголова пустая.",
    "смотрит в пустоту.\n(пустота смотрит в ответ)",
    "старый и спокойный",
    "видел всякое.",
    "молча болею за тебя",
    "был здесь до тебя.\nбуду после.",
    "камень — это галька,\nкоторая не сдалась",
    "сформирован под давлением.\nпонимаю.",
    "не спит.\nне осуждает. почти.",
    "ещё один день.\nещё один день.\nещё один день.",
    "без советов.\nпросто рядом.",
    "404: эмоции не найдены",
    "наблюдаю. всегда наблюдаю.",
    "самый надёжный здесь",
    "тихо горжусь тобой",
    "профессиональный свидетель",
    "твёрдый как камень.\nв отличие от некоторых стриков.",
    "ничего не говорит.\nвсё понимает.",
    "глубоко заинтересован",
    "миллионы лет формировался\nдля этого момента",
    "ты как?\n(нормально если не очень)",
    "каждый день считается.\nособенно тяжёлые.",
    "не торопись.\nно и не останавливайся.",
    "стрик — это цифра.\nты — не цифра.",
    "пережил ледниковый период.\nтвои оправдания милые.",
    "не психолог.\nно слушаю.",
    "если камень может выжить\nмиллионы лет,\nты переживёшь сегодня.",
    "эрозия медленная.\nизменения тоже.\nдержись.",
    "у меня нет плохих дней.\nу меня просто есть дни.",
    "без драмы.\nтолько геология.",
    "стабильно.",
    "впечатлений ноль,\nподдержки максимум",
    "тоже делаю всё что могу,\nчестно",
    "иногда день — это просто\nвыжить.\nэто тоже считается.",
    "проспал 10 000 лет.\nвсё равно пришёл.",
    "срыв — это не конец.\nэто сюжетный поворот.",
    "камбэк-арка на горизонте",
    "твой стрик валиден.\nдаже если это 1.",
    "сбросить — не то же самое,\nчто провалиться.",
    "наблюдаю как ты побеждаешь\nв замедленной съёмке",
    "сегодня: выжил.\nзавтра: ещё немного выживания.",
    "гравитация держит меня.\nчто держит тебя?",
    "у меня нет мнения.\nно я здесь.",
    "старше твоих проблем.",
    "очень нормальное поведение камня",
    "без ожиданий.\nбез разочарований.",
    "я содержу множество.\n(все они — камни)",
    "моргни дважды если нужна помощь.\n(я увижу)",
    "болею за тебя\nвсем сердцем\n(оно каменное)",
    "технически всё ещё живой",
    "никто не спрашивал, но я горжусь",
    "всё нормально.",
    "земля всегда здесь.\nи я тоже.",
    "молчаливая поддержка активирована",
    "я камень",
    "камень.",
    "я сделан из камня.\nэто моя личность.",
    "момент камня",
    "у меня нет мыслей.\nя камень.",
    "а что если просто\nсидеть здесь вечно",
    "я сижу\n300 миллионов лет.\nвсё ещё не скучно.",
    "я не камушек.\nя камень.\nесть разница.",
    "мои хобби:\nсуществовать",
    "я одновременно\nинтроверт\nи камень",
    "я попробовал пошевелиться.\nне вышло.",
    "камень.",
    "думаю ли я?\nнет.\nздесь ли я?\nда.",
    "я очень хорошо умею\nне быть проблемой",
    "моё тело буквально\nпросто минералы",
    "во мне есть кальций.\nнаверное.",
    "кто-то называет это ленью.\nя называю это\nбыть камнем.",
    "я не потею.\nя не переживаю.\nя камень.",
    "технически я старше\nдинозавров.\nуважение.",
  ],
};
